### ISSUE TITLE
为什么要自己实现 ViewPager？

### ISSUE THREAD

**Issue by cameoh** [boycy815/PinchImageView#10]
从可维护性的角度，更合适的做法是继承 ViewPager，重写部分方法。为什么要整个重写 ViewPager？希望能改进一下。

**Comment by boycy815** [comment]
ViewPager没有把需要覆盖的地方开放出来，是个private方法。

**Comment by liyujiang-gzu** [comment]
ViewPager没有把需要覆盖的地方开放出来，是个private方法。从可维护性的角度，更合适的做法是继承 ViewPager，重写部分方法，可以使用反射额
