### ISSUE TITLE
旋转后出现问题

### ISSUE THREAD

**Issue by kanyuan** [boycy815/PinchImageView#11]
matrix.postRotate(90, mImageView.getWidth()/2, mImageView.getHeight()/2);
mImageView.outerMatrixTo(matrix, 200);
当outerMatrixTo接口传递一个旋转的matrix时，放大后，图片消失在视图中。
有没有什么办法解决？

**Comment by boycy815** [comment]
暂时不支持旋转，后续加下这个功能
