### ISSUE TITLE
viewpager冲突

### ISSUE THREAD

**Issue by ghost** [boycy815/PinchImageView#12]
跟viewpager联用有冲突...使用你demo里面自己写的viewpager也是一样...

**Comment by boycy815** [comment]
怎么个冲突法？

**Comment by dashugege** [comment]
viewpager联用有冲突，你吧图片 稍微放大一点，（如果不可以，继续放大，可能会有一个零界点），然后viewpager 无法滑动，切换页面。
if ((dx != 0 && !isGutterDrag(mLastMotionX, dx) && canScroll(this, false, (int) dx, (int) x, (int) y))
                        || isDisallowDrag(dx)) {
                    // Nested view has scrollable area under this point. Let it be handled there.
                    mLastMotionX = x;
                    mLastMotionY = y;
                    mIsUnableToDrag = true;
                    return false;
                }
跟踪，图片放大，滑动，会一直执行这个if。所以viewpager无法滑动

**Comment by boycy815** [comment]
fixed
