### ISSUE TITLE
有些超大的图片加载的时候不显示

### ISSUE THREAD

**Issue by NiLuogege** [boycy815/PinchImageView#15]
图片地址: http://wimg.spriteapp.cn/x/640x400/ugc/2016/09/21/57e1bf635a4e2.jpg
这个图片的尺寸是 640*17195.

加载相对小一些的图片是非常完美的,但是上面提到的这张图片就是加载不进去 也不报错,我试了一下在photoView中是可以显示出来的,imageView中也是可以的.希望有时间可以看看这个问题.(不止上面提到的这一张图片有问题,还有其他的比如 http://wimg.spriteapp.cn/x/640x400/ugc/2016/09/23/57e45fc869587.jpg)

最近我也在看你的这个控件.非常的赞

**Comment by boycy815** [comment]
在demo中加在不出来是ImageLoader的问题，ImageLoader在加在大图的时候OOM了，在logcat里会有日志。你可以尝试使用demo中的分片加载来加载大图。

**Comment by LongAgoLong** [comment]
分片加载如何支持glide？
