### ISSUE TITLE
Picasso加载图片闪烁问题

### ISSUE THREAD

**Issue by xiedaibin** [boycy815/PinchImageView#17]
在Demo应用中我将图片加载方式由ImageLoader 改 为Picasso方式出现闪烁问题。
 //Global.getImageLoader(getApplicationContext()).displayImage(image.getUrl(100, 100), piv, thumbOptions);
Picasso.with(PagerActivity.this).load(image.getUrl(100,100)).into(piv);

//Global.getImageLoader(getApplicationContext()).displayImage(image.getUrl(image.getOriginWidth(), image.getOriginHeight()), piv, originOptions);
 Picasso.with(PagerActivity.this).load(image.getUrl(image.getOriginWidth(), image.getOriginHeight())).into(piv);

**Comment by mrzhqiang** [comment]
Picasso.with(Context).load(Path).noFade().into(ImageView);
闪烁是Picasso自带的淡入淡出效果吧？禁掉它！
