### ISSUE TITLE
长图展示为问题

### ISSUE THREAD

**Issue by litonghui** [boycy815/PinchImageView#23]
加载一个长图是可以让图片宽度适配整个屏幕，目前是中间一个长条。

**Comment by boycy815** [comment]
在setImageDrawable的时候通过宽高计算下mOuterMatrix值。

**Comment by VliceZ** [comment]
通过gilide加载网络图片会出现图片距离两边屏幕大概有20dp的间距是因为什么原因呢

**Comment by boycy815** [comment]
更新了demoi a1703de
