### ISSUE TITLE
 不支持在布局中设置android:scaleType="fitXY"

### ISSUE THREAD

**Issue by 2862339302** [boycy815/PinchImageView#25]
设置android:scaleType="fitXY",仍然没有宽度全屏

**Comment by boycy815** [comment]
这样会导致宽高不等比，你希望达到怎么样的效果？

**Comment by 2862339302** [comment]
在做一个壁纸功能，所以要图片不管什么比例都全屏，已改为图片总是按屏幕大小裁剪，所以总是能全屏，使用没问题了。这个控件很好用，如果能支持imageView的scaleType设置就更好了。

**Comment by YuanTiger** [comment]
我也在做壁纸的功能。
我想让图片在加载出来时，直可以占满屏幕。
比如用户选择了一张正方形的图片，直接将这张图片放大到高度占满屏幕，宽度可以进行左右滑动展示。
这个控件还是很好用的，许多项目里我都用了这个控件。

**Comment by zheng351138312** [comment]
怎么实现把缩放的最小限制在最长一边的

**Comment by zheng351138312** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
