### ISSUE TITLE
看代码过程中有一点疑问

### ISSUE THREAD

**Issue by chentuoge** [boycy815/PinchImageView#33]
Hi, 我是一个android程序员，github上发现了你做的PincnImageView这个神奇的库。
我在使用这个库的过程中，有一点疑问：

图片放大缩小的动画过程中，除了对matrix的放大缩小之外，为什么还要同步进行一个mask的放大缩小动画？

我尝试注视掉相关的代码，也能正常运行，出现预期的效果

能不能简单的给我解释一下，mask存在的意义....

谢谢啦

**Comment by boycy815** [comment]
为了实现demo中的点击放大功能
