### ISSUE TITLE
存在性能问题 一直渲染绘制

### ISSUE THREAD

**Issue by ButterflyCabin** [boycy815/PinchImageView#36]
在GridView中使用发现PinchImageView一直在渲染绘制
只在显示数据的情况下有一直渲染绘制，点击后就没有一直渲染绘制，回来又有一直渲染绘制。
@Override
    protected void onDraw(Canvas canvas) {
        //在绘制前设置变换矩阵
        if (isReady()) {// debug这一直返回true
           ……
            setImageMatrix(getCurrentImageMatrix(matrix));
           ……
        }
        ……
    }

onDraw()->isReady()->setImageMatrix()->invalidate()->onDraw()->isReady()…进入死循环…onDraw()->isReady()->setImageMatrix()->invalidate()
手机打开Profile GUP rendering 选 On screen as bars 显示一直在渲染绘制

**Comment by 4apple** [comment]
/*HugeImageRegionLoader*/
    public void loadRegion(int id, int sampleSize, Rect sampleRect) {
        if (mDecoder != null) {
            String key = genKey(id, sampleSize);
//            Log.d(TAG, "loadRegion:id=" + id + ",sampleSize=" + sampleSize + ",sampleRect=" + sampleRect);
            if (mRecycleCommands.containsKey(key)) {
                mRecycleCommands.remove(key);
            }
            if (mLoadedBitmaps.containsKey(key)) {
                dispatchRegionLoad(id, sampleSize, sampleRect, mLoadedBitmaps.get(key));
            } else if (!mTasks.containsKey(key)) {//修改这行试试
                LoadTask task = new LoadTask(id, sampleSize, sampleRect);
                mTasks.put(key, task);
                task.execute();
            }
        }
    }
/*HugeImageRegionLoader.java*/
        @Override
        protected void onPostExecute(Bitmap result) {
            final String key = genKey(mId, mSampleSize);
            if (result != null && mDecoder != null) {
                if (!mRecycleCommands.containsKey(key)) {
                    if (mLoadedBitmaps.containsKey(key)) {
                        mLoadedBitmaps.get(key).recycle();
                    }
                    mLoadedBitmaps.put(key, result);
                    dispatchRegionLoad(mId, mSampleSize, mSampleRect, result);
                }
            }
            mTasks.remove(key);//关键这行
        }

**Comment by boycy815** [comment]
我这里没重现，setImageMatrix不会调用invalidate的
