### ISSUE TITLE
图片缩放后得到imageview区域显示的图片

### ISSUE THREAD

**Issue by chrissen0814** [boycy815/PinchImageView#46]
作者您好

本人在使用您的控件的过程中需要获取到缩放后imageview显示部分的图片，我看了您的代码，似乎没有找到api , 不知道该如何获取。

希望能得到您的回复与解答

谢谢！

**Comment by boycy815** [comment]
没听懂你的问题，缩放并未改变图片本身，仅仅是展示的位置和大小改变。
