### ISSUE TITLE
addOuterMatrixChangedListener双击放大，再双击缩小得到的ImageBound不一样

### ISSUE THREAD

**Issue by 1371030** [boycy815/PinchImageView#47]
例如：
进入activity显示图片，并addOuterMatrixChangedListener
最后显示的结果是  RectF(0.0, 633.6239, 1440.0, 1709.3761)

这里双击放大，再双击缩小

得到

 RectF(1.2207031E-4, 633.62415, 1440.0001, 1709.3763)

**Comment by boycy815** [comment]
精度丢失问题，你这边的场景需要这么高精度？
