### ISSUE TITLE
Glide拿不到监听回调

### ISSUE THREAD

**Issue by rainfoam** [boycy815/PinchImageView#48]
大图很多都是全屏参看的,全屏加载需要知道Loading,error,success状态. 当把该控件findviewbyid转化为Imageview后, 通过Glide加载,使用监听器RequestListener,发现拿不到任何回调,原因未知, findviewbyid为此自定义控件也不行, 用普通的Imageview就可以拿到回调.  Glide版本3.7.0.

**Comment by boycy815** [comment]
没复现这个问题
