### ISSUE TITLE
如何获取点击位置对应的图片位置

### ISSUE THREAD

**Issue by jingchangfa** [boycy815/PinchImageView#49]
// 对方法进行扩展～（直接改的源码）
        public boolean onSingleTapConfirmed(MotionEvent e) {
            //触发点击
            if (mOnClickListener != null) {
                mOnClickListener.onClick(PinchImageView.this);
            }
            if (null != imageOnClickListener){
                // 获取触摸点的坐标 x, y
                float x = e.getX();
                float y = e.getY();
                // 目标点的坐标
                float dst[] = new float[2];
                // 获取到ImageView的matrix
                Matrix imageMatrix = getImageMatrix();
                // 创建一个逆矩阵
                Matrix inverseMatrix = new Matrix();
                // 求逆，逆矩阵被赋值
                imageMatrix.invert(inverseMatrix);
                // 通过逆矩阵映射得到目标点 dst 的值
                inverseMatrix.mapPoints(dst, new float[]{x, y});
                float dstX = dst[0];
                float dstY = dst[1];
                // 获取图片的大小
                float drawWidth = getDrawable().getBounds().width();
                float drawHeight = getDrawable().getBounds().height();
                float deviceX = dstX/drawWidth;
                float deviceY = dstY/drawHeight;
                // 判断dstX, dstY在Bitmap上的位置即可
                if (!(deviceX<0 || deviceX>1 || deviceY<0 || deviceY>1)){
                    imageOnClickListener.onClick(deviceX,deviceY);
                }
            }
            return true;
        }

**Comment by boycy815** [comment]
getCurrentImageMatrix可以获得当前图片的变换矩阵。即原图中的点p1经过变换矩阵得到的p2就是显示在屏幕上的点（相当于ImageView坐标系）。所以如果你有p2，通过矩阵逆变换，就可以获得p1。
