### ISSUE TITLE
配合Glide使用

### ISSUE THREAD

**Issue by wuzheng4android** [boycy815/PinchImageView#52]
配合Glide使用加载小图的时候 会拉伸图片尺寸,请问怎么修改

**Comment by boycy815** [comment]
目前不支持最小尺寸小于FitCenter的模式。会考虑支持这种模式。

**Comment by boycy815** [comment]
PinchImageView默认使用的是Fit Center缩放模式。因此小图可能体验不是很好。可以继承后覆盖getInnerMatrix方法，自定义scaleMode
