### ISSUE TITLE
请问，up主怎么改造了viewpager

### ISSUE THREAD

**Issue by Dawson-huang** [boycy815/PinchImageView#57]
#16

**Comment by Dawson-huang** [comment]
我用的是[https://github.com/youth5201314/banner](url)控件，这位大神用的是viewpager2，这有影响吗，目前呈现的效果跟 #16 一样

**Comment by Heinoc** [comment]
@Dawson-huang 
PinchImageView#onTouchEvent方法中如下修改：
![image](https://github.com/boycy815/PinchImageView/assets/5534122/304aa3c9-a4db-4038-a01f-fa896b921c94)

**Comment by jarlen** [comment]
我收到你的邮件啦，我会尽快回复的哦，谢谢

Only efforts can prove that I existed in this world  ---jarlen
