### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by EvilBT** [boycy815/PinchImageView#6]
配合ViewPager划动久了会出现内存不足

**Comment by boycy815** [comment]
example做的比较粗糙，内存控制得不好是有可能的。可能是这几个方面：
1. 图片尺寸太大，一次性占用太多内存
2. ImageLoader并没有及时回收图片占用的资源

**Comment by boycy815** [comment]
已经做了内存优化，在不是当前页时不加载大图，加载100x100的小图，到当前页后再替换成大图
