### ISSUE TITLE
长图展示不了

### ISSUE THREAD

**Issue by dasamanren** [boycy815/PinchImageView#8]
你好,这个控件很好用,我十分喜欢,但是不能展示长图,我想问问,能不能优化一下,让长图也能展示,谢谢

**Comment by boycy815** [comment]
长图理论上能展示，你指的不能展示是什么情况？

**Comment by dasamanren** [comment]
http://ww4.sinaimg.cn/large/7fd54a81jw1f35fyioy80j20go68i4np.jpg
比如这张图,宽高比是width: "600",
height: "8082",这样的图片就看不了,你试试

**Comment by boycy815** [comment]
我试了是可以的，有错误日志么？

**Comment by boycy815** [comment]
你用email联系我，这样效率高一些。

**Comment by boycy815** [comment]
如果出现oom可以试试demo中第三个例子，使用了分片加载策略。

**Comment by dasamanren** [comment]
ok,可以了,谢啦,用的第三种方式,先把图片弄到本地,然后把地址转成file://的uri传进去展示
