### ISSUE TITLE
大图加载不了

### ISSUE THREAD

**Issue by laobie** [boycy815/PinchImageView#9]
http://img14.poco.cn/mypoco/myphoto/20130310/23/37946792201303102310055767758932315_004.jpg
这张也加载不出来，作者可以试试

**Comment by laobie** [comment]
@boycy815 
可以直接本地 也加载不出来。

**Comment by laobie** [comment]
真机上加载不出来，模拟器上直接OOM

**Comment by boycy815** [comment]
可以试试demo中第三个例子，里面使用了分片加载可以防止大图OOM。
由于分片加载涉及到内存管理，线程管理等问题，所以为了保持控件指责单一没有把它集成进去，只是作为一个example提供出来。
